### ISSUE TITLE
XSD for kodelister

### ISSUE THREAD

**Issue by henbjo** [Skatteetaten/skattemeldingen#4]
Kodelistene som ligger under [docs/documentation/informasjonsmodell/kodeliste](https://github.com/Skatteetaten/skattemeldingen/tree/master/docs/documentation/informasjonsmodell/kodeliste) har alle et felles format.

Jeg ønsker at dere publiserer XSD-en for disse, slik at det er lettere å omforme disse til kjørbar kode.

**Comment by bjerkeli** [comment]
Lagt xsd for kodeliste
