### ISSUE TITLE
Feil Content-Type på API med XML-respons

### ISSUE THREAD

**Issue by henbjo** [Skatteetaten/skattemeldingen#5]
### Beskrivelse

API-er som produserer XML-respons har Content-Type header `application/json`.

### Forventet oppførsel
Eksempel på request
```
GET /api/eksterntapi/formueinntekt/skattemelding/2020/05*******48
```
skal gi response med Content-Type `text/xml` eller tilsvarende
```
200 OK
Content-Type: text/xml
[...]
<skattemeldingerOgNaeringsopplysningerforespoerselResponse xmlns="no:skatteetaten:fastsetting:formueinntekt:skattemeldingerognaeringsopplysninger:forespoersel:response:v1">....</skattemeldingerOgNaeringsopplysningerforespoerselResponse>
```

### Faktisk oppførsel
Eksempel på request
```
GET /api/eksterntapi/formueinntekt/skattemelding/2020/05*******48
```
gir response med Content-Type `application/json`, selv om innholdet i body er XML
```
200 OK
Content-Type: application/json
[...]
<skattemeldingerOgNaeringsopplysningerforespoerselResponse xmlns="no:skatteetaten:fastsetting:formueinntekt:skattemeldingerognaeringsopplysninger:forespoersel:response:v1">....</skattemeldingerOgNaeringsopplysningerforespoerselResponse>
```

### For å reprodusere
`GET`-request til endepunkt `https://mp-test.sits.no/api/eksterntapi/formueinntekt/skattemelding/2020/<identifikator>` med gyldig access token fra ID-porten med scope `skatteetaten:skattemelding`.

**Comment by martinunhjem** [comment]
Denne skal nå være løst, men skrik ut om du skulle fortsatt oppleve dette problemet. 
Ta også gjerne kontakt direkte på mail
