### ISSUE TITLE
Accept header text/xml på request til API med XML-respons gir 406 Unacceptable

### ISSUE THREAD

**Issue by henbjo** [Skatteetaten/skattemeldingen#6]
### Forventet oppførsel
Eksempel på request
```
GET /api/eksterntapi/formueinntekt/skattemelding/2020/05*******48
Accept: text/xml
```
skal gi response
```
200 OK
Content-Type: text/xml
[...]
<skattemeldingerOgNaeringsopplysningerforespoerselResponse xmlns="no:skatteetaten:fastsetting:formueinntekt:skattemeldingerognaeringsopplysninger:forespoersel:response:v1">....</skattemeldingerOgNaeringsopplysningerforespoerselResponse>
```

### Faktisk oppførsel
Eksempel på request
```
GET /api/eksterntapi/formueinntekt/skattemelding/2020/05*******48
Accept: text/xml
```
gir response
```
406 Unacceptable
[...]
```
selv om API-et produserer respons av typen XML.

### For å reprodusere
`GET`-request til endepunkt `https://mp-test.sits.no/api/eksterntapi/formueinntekt/skattemelding/2020/<identifikator>` med gyldig access token fra ID-porten med scope `skatteetaten:skattemelding`.

**Comment by martinunhjem** [comment]
Dette skal nå være løst. 
Opplever du fortsatt problemer, så si i fra
